# Generated by Django 5.2.3 on 2025-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_beds', models.IntegerField()),
                ('icu_beds', models.IntegerField()),
                ('ventilators', models.IntegerField()),
                ('oxygen_cylinders', models.IntegerField()),
                ('doctors', models.IntegerField()),
                ('nurses', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
