# Generated by Django 5.2.3 on 2025-09-10 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField()),
                ('icu_beds', models.IntegerField()),
                ('occupied_icu', models.IntegerField()),
                ('oxygen_cylinders', models.IntegerField()),
                ('occupied_oxygen', models.IntegerField()),
                ('ventilators', models.IntegerField()),
                ('occupied_ventilators', models.IntegerField()),
                ('doctors', models.IntegerField()),
                ('occupied_doctors', models.IntegerField()),
                ('nurses', models.IntegerField()),
                ('occupied_nurses', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='hospitals.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'timestamp'], name='hospitals_r_hospita_e7600a_idx')],
            },
        ),
    ]
