# Generated by Django 5.2.3 on 2025-09-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_resourcesnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='icu_beds',
        ),
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='nurses',
        ),
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='oxygen_cylinders',
        ),
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='total_beds',
        ),
        migrations.RemoveField(
            model_name='resourcesnapshot',
            name='ventilators',
        ),
    ]
